name: pgm-book-club
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - jupyterlab=0.35.4
  - pandas=0.24.0
  - numpy=1.16.2
  - pymc3=3.8
  - theano=1.0.4
  - scipy=1.2.1
  - seaborn=0.9.0
  - matplotlib=3.0.3
  - scikit-learn=0.22.1
  - mkl-service=2.0.2
  - statsmodels=0.9.0
  - jupyter_contrib_nbextensions=0.5.1

